"""adding suggested columns

Revision ID: 52cb9de78f9e
Revises: f4382236851b
Create Date: 2024-09-17 14:20:56.702805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cb9de78f9e'
down_revision = 'f4382236851b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('books', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'deleted_at')
    op.drop_column('books', 'is_deleted')
    # ### end Alembic commands ###
