"""add holder details to books table

Revision ID: f4382236851b
Revises: 91f0513fd139
Create Date: 2024-09-17 13:59:20.683431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4382236851b'
down_revision = '91f0513fd139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('holder_id', sa.UUID(), nullable=True))
    op.add_column('books', sa.Column('holder_email', sa.String(), server_default='example@mail.com', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'holder_email')
    op.drop_column('books', 'holder_id')
    # ### end Alembic commands ###
